steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "${_IMAGE}"
      - "--build-arg"
      - "NEXT_PUBLIC_API_BASE_URL=${_API_BASE_URL}"
      - "."
images:
  - "${_IMAGE}"
